language: scala
jdk: oraclejdk8

services:
  - docker

before_install:
- docker pull sonarqube:lts-alpine
- docker run -d --name sonarqube -p 9000:9000 -p 9092:9092 sonarqube

script:
   - sbt ^scripted